remote_theme: riggraz/no-style-please
title: l-e
author: l-e
favicon: "favicon.png"
theme_config:
  appearance: "light"
  back_home_text: "⇤ home"
  date_format: " "
  show_description: false
  
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-feed
  
relative_links:
  enabled: true
  collections: true
  
