remote_theme: riggraz/no-style-please
title: suivez le guide
author: l-e
description: ce blog dispose d'un [flux RSS](https://1363v4.github.io/feed.xml)
favicon: "favicon.png"
theme_config:
  appearance: "light"
  back_home_text: "⇤ home"
  date_format: " "
  show_description: true
  
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-feed
  
relative_links:
  enabled: true
  collections: true
  